### ISSUE TITLE
modifyEntity appears to be unable to alter experience drops

### ISSUE THREAD

**Issue by Joziah2** [liopyu/EntityJs#13]
When using modifyEntity and modifyBuilder, the amount of xp dropped by the mob does not seem to be affected by the experienceReward alteration. 

EntityJS 0.3.7, Forge 1.20.1

Code used:

//Startup Event
EntityJSEvents.modifyEntity(event => {
    
    console.info("Attempting Boss Alterations");
    //Mutant Zombie (Boss 1)
    
    event.modify('minecraft:zombie', modifyBuilder => {
        // Since zombies extend the PathfinderMob class, a ModifyPathfinderMobBuilder will be provided
        modifyBuilder.experienceReward(killedEntity => 100);
    });
    
    event.modify('mutantmonsters:mutant_zombie', modifyBuilder => {
        // Since zombies extend the PathfinderMob class, a ModifyPathfinderMobBuilder will be provided
        modifyBuilder
        .experienceReward(killedEntity => 300);
    });  

});

**Comment by liopyu** [comment]
Try EntityJS 0.3.8 and tell me if that fixes the issue.

**Comment by Joziah2** [comment]
Just tried EntityJS 0.3.8-It works now! Thanks so much!
