### ISSUE TITLE
[Feature Request]: Registering boat entities

### ISSUE THREAD

**Issue by mosharky** [liopyu/EntityJs#6]
Registering a boat alone would be pretty darn cool, but what if it could have:
- Customizable animations and models
- Customizable amounts of passengers
- Boat drift (I guess this could just be `.tick()` + adding to boat velocity?)
- An NBT tag to change the boat texture (like vanilla)
- Boat interaction:
    - Right-click the boat with a chest: 
        - Add a chest & update the boat inventory
        - Show it on the boat entity
        - Possible to have more than one chest
    - Right-click the boat with a lead: 
        - Make the boat follow the lead
        - Reflect it on the boat model
        - Right-click again to untie the boat
    - Right-click with a (custom item) paddle: 
        - Enable player boat controls
        - Add paddles to the boat model
    - Shift-right-click to remove stuff added to the boat (like the chests or paddles)

The inspiration for most of this suggestion came from [this TerraFirmaCraft addon](https://terrafirmacraft.github.io/Field-Guide/en_us/firmaciv/watercraft.html)

**Comment by liopyu** [comment]
i just looked into it and it seems this is possible with geckolib's recent fixes to non living entity rendering, i'll have to do this when i have time after i add part entities and some other things ect, very cool suggestion!

**Comment by mosharky** [comment]
Ah awesome! Hope to see it :D

**Comment by liopyu** [comment]
Boat builder has been added as of 1.19.2 0.1.0 & 1.20.1 0.0.9
