### ISSUE TITLE
[Question] Are there any ways to animate non-alive entities like snowballs / arrows using Gecko models?

### ISSUE THREAD

**Issue by para-dichloro-benzene** [liopyu/EntityJs#7]
I want to add some fancy animation to my custom throwables, after placing the files in the correct path, I added the line
>       .addAnimationController('exampleController', 1, event => {
>            event.thenLoop('test')
>            return true; // Indicate successful animation setup
>        })

into the startup registry code.

But then the game crashes at start and tells me
 `Error in 'StartupEvents.registry': TypeError: Cannot find function addAnimationController in object ProjectileEntityJSBuilder[kubejs:manure_entity].`

I am not sure if I did anything wrongly or it is not possible to do that with EntityJS right now.

**Comment by liopyu** [comment]
this would have to be implemented as only the nonliving entity builder will have geckolib animation capabilities, what minecraft version are you on and is this forge or fabric?

**Comment by para-dichloro-benzene** [comment]
> this would have to be implemented as only the nonliving entity builder will have geckolib animation capabilities, what minecraft version are you on and is this forge or fabric?

I am on 1.20.1 with forge 47.3.5. Would be glad to see it implemented ;)

**Comment by liopyu** [comment]
should have it out by tomorrow

**Comment by liopyu** [comment]
fixed as of version 0.2.9 [3616866](https://github.com/liopyu/EntityJS/commit/36168663b9ecba0c05d93535e50ac84afccf08e9)
```javascript
StartupEvents.registry("entity_type", event => {
	event.create("wyrm", "entityjs:geckolib_projectile")
})
```

**Comment by para-dichloro-benzene** [comment]
The entityjs:geckolib_projectile is using kubejs/assets/kubejs/textures/entity/xxx.png rather than kubejs/assets/kubejs/textures/entity/projectiles/xxx.png for entityjs:projectile, is that intended?

**Comment by liopyu** [comment]
yes, now that it uses geckolib modelling it'll use the same locations as normal geckolib entities
![image](https://github.com/user-attachments/assets/86b922f3-972d-4192-b017-d97bac57f222)
