### ISSUE TITLE
Crashes on dedicated server on boot

### ISSUE THREAD

**Issue by cwielder** [liopyu/EntityJs#8]
Report an issue or feature request

**Mod Version:**
0.3.1

**Minecraft Version:**
1.20.1

**Minecraft Modloader:**
Forge

**Describe the Bug/Feature Request:**
The mod causes dedicated servers to crash on launch due to accessing client-only classes.

**Screenshots or Logs:**
https://gist.github.com/NeoCamelot/9f67bc937c0c83e5361e7c3ec5f7133d

**Comment by liopyu** [comment]
yeah will be fixed within the hour

**Comment by liopyu** [comment]
Fixed as of EntityJS version [0.3.2](https://www.curseforge.com/minecraft/mc-mods/entityjs/files/5705274)
